spring.application.name=jobboard
spring.datasource.url=jdbc:mysql://localhost:3306/jobboard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.profiles.active=dev


# file upload
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.web.resources.static-locations=classpath:/static/,file:uploads/
server.port=8080

jwt.secret=mySuperSecretKeyForJwtToken123456789
jwt.expiration=86400000

# Alibaba Cloud Qwen AI
qwen.api.key=sk-638906e5f1e24e709a49103bd2b9b388
qwen.model=qwen-plus
qwen.api.url=https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions